from src.PyperText.html import Script
from src.PyperText.htmlEntry import Entry,NumberEntry
from src.PyperText.htmlButton import Button
from src.PyperText.htmlHeader import Header
from src.PyperText.htmlImage import Image
from src.PyperText.htmlModifiers import italics,bold,underline
from src.PyperText.htmlTextbox import Textbox
from os import system
system("Cls")
#Make sure logs all fit same memo: Creating {Widget} with {Custom|Default} Header
#Working:Entry(Reg,Number),Script(Could look better),Button, Header(1-6), Image,italics,bold,underline, Textbox
#Broken:None
myScript=Script("test.html")
myScript.addCustomHeader("lang=\"en\"")
myEntry=Entry()
myEntry.setValue("val")
myEntry.finalize()
MyNumberEntry=NumberEntry()
MyNumberEntry.setValue(2)
MyNumberEntry.setID("Num")
MyNumberEntry.finalize()
myButton=Button()
myButton.setText(italics("Val").form())
myButton.setID("Cool")
myButton.finalize()
myHeader1=Header(1)
myHeader1.setText(bold("Header 1"))
myHeader1.setID("H1")
myHeader1.finalize()
myHeader2=Header(2)
myHeader2.setText(underline("Header 2"))
myHeader2.setID("H2")
myHeader2.finalize()
myHeader3=Header(3)
myHeader3.setText("Header 3")
myHeader3.setID("H3")
myHeader3.finalize()
myHeader4=Header(4)
myHeader4.setText("Header 4")
myHeader4.setID("H4")
myHeader4.finalize()
myHeader5=Header(5)
myHeader5.setText("Header 5")
myHeader5.setID("H5")
myHeader5.finalize()
myHeader6=Header(6)
myHeader6.setText("Header 6")
myHeader6.setID("H6")
myHeader6.finalize()
myImage=Image("test.jpg")
myImage.setAlternativeText("Test Image")
myImage.setSize((500,500))
myImage.finalize()
myText=Textbox()
myText.setID("txt")
myText.setText("This is text")
myText.finalize()
myScript.addWidget(myEntry)
myScript.addWidget(MyNumberEntry)
myScript.addWidget(myButton)
myScript.addWidget(myHeader1)
myScript.addWidget(myHeader2)
myScript.addWidget(myHeader3)
myScript.addWidget(myHeader4)
myScript.addWidget(myHeader5)
myScript.addWidget(myHeader6)
myScript.addWidget(myImage)
myScript.addWidget(myText)
myScript.addScript("test.js")
myScript.createAndWrite()
